name: Manual build API example

on:
  pull_request:
    paths:
      - ".github/workflows/example-build.yml"
      - "example/**"
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  local-ci:
    name: Example app
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Start containers
        run: docker compose up -d --build
        working-directory: "./example"

      # Runs positive Schemathesis tests
      - uses: schemathesis/action@v1
        continue-on-error: true
        with:
          # A local API schema location
          schema: "http://127.0.0.1:5123/openapi.json"
          # Set your token from secrets
          token: ${{ secrets.SCHEMATHESIS_TOKEN }}
          max-examples: "10"
          # To avoid failing the build
          args: "-E does-not-exist"

      - name: Stop containers
        if: always()
        run: docker compose down
        working-directory: "./example"
