name: Hypothesis tests

on:
  schedule:
    # Every day at 00:00
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  hypothesis-tests:
    name: Hypothesis tests with CI profile
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: hynek/setup-cached-uv@v2

      - run: uvx --from=".[tests]" pytest -m hypothesis -m hypothesis_nested --hypothesis-profile CI test
